# autogenerated by txs
#include:amssymb
#include:epsfig
#include:graphicx
#include:moreverb
#include:parskip
\Abgabeblatt{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}{arg7}{arg8}#S
\Arbblatt{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}{arg7}{arg8}{arg9}#S
\bob#S
\grenzop{arg1}{arg2}{arg3}#S
\langrechtspfeil{arg1}{arg2}#S
